### ISSUE TITLE
一加1 android 4.4.4 statusbar 不支持设置深色状态栏图标

### ISSUE THREAD

**Issue by hsiunien** [msdx/status-bar-compat#1]
你好。我在一加一android4.4.4手机上用你的代码测试statusbar的文字颜色没有变成黑色，也就是看不清时间。在nexus6上是好的。

**Comment by msdx** [comment]
文字颜色改变是在android 6.0以上才能支持，因为它所使用的API是在Android 23才引入的。Android 4.4.4来修改状态栏颜色，实际上是先把状态栏设为半透明，然后添加一个与状态栏同样大小的View并设置这个View的背景来实现的。正常来说，由于状态栏是半透明的（按不同版本会有由半透明到全透明渐变，或者是全部半透明，如nexus5），是不会看不见的。但是国内的厂商会把它改为全透明，针对这些厂商这种做法，目前我也没有好的解决方法。

**Comment by hsiunien** [comment]
大概就是这样。 其实如果是半透明的也还好，但是是几乎看不清了 
![qq 20160621205336](https://cloud.githubusercontent.com/assets/5487535/16230110/7c452142-37f2-11e6-9444-02ab1af1a479.png)

**Comment by msdx** [comment]
所以国内的手机适配起来问题多，本来应该是像项目介绍上的第一张图那样的效果的。因此，许多应用会尽量避开把状态栏设置成接近于白色的情况。

**Comment by msdx** [comment]
我目前参考一些资料已经适配了小米和魅族，但是找不到一加的ROM的相关API，微博联系了他们，但是好像还没明白我的意思。

**Comment by msdx** [comment]
第三方ROM修改问题。第三方ROM把半透明状态栏改为全透明状态栏，但未提供将状态栏字体及图标设置为深色的方法。

**Comment by msdx** [comment]
API 23以下没有设置深色图标的接口。
