### ISSUE TITLE
Samsung SM-N9006 4.3

### ISSUE THREAD

**Issue by hxkdidi** [msdx/status-bar-compat#13]
Samsung SM-N9006 4.3无法改变颜色，状态栏始终是黑色

**Comment by msdx** [comment]
仅支持4.4.2(API 19)以上

**Comment by hxkdidi** [comment]
4.4.2以下透明的话，方案我有，只是这个方案到5.0以上会出现一个灰色半透明蒙层

**Comment by msdx** [comment]
你说的是全屏但在顶部留出空白的一部分吗？

**Comment by msdx** [comment]
你可以判断系统版本号，如果小于19就用你的方案。
