### ISSUE TITLE
无法设置全屏。

### ISSUE THREAD

**Issue by yingshirun** [msdx/status-bar-compat#16]
你好，使用你的库后在页面动态修改window的全屏状态时，全屏效果就没有了，状态栏的颜色会强制修改我的全屏页面
代码如下：
     setContentView(R.layout.activity_exit);
        StatusBarCompat.setStatusBarColor(this, getResources().getColor(R.color.statusBarColor));
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,  WindowManager.LayoutParams.FLAG_FULLSCREEN);

**Comment by msdx** [comment]
既然是全屏，那就不需要去设置状态栏。
另外，设置全屏请在调用StatusBarCompat之前进行设置，我代码里有如下检查：
```java
        if ((window.getAttributes().flags & WindowManager.LayoutParams.FLAG_FULLSCREEN) > 0
                || StatusBarExclude.exclude) {
            return;
        }
```
(https://github.com/msdx/status-bar-compat/blob/master/library/src/main/java/com/githang/statusbar/StatusBarCompat.java)

**Comment by msdx** [comment]
如果全屏的代码需要在调用StatusBarCompat之后调用，建议试下如下做法：
5.0以上设置状态栏颜色需要添加该标志位`WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS`，试下去掉。
