### ISSUE TITLE
MIUI新版状态栏黑色字符修改实现方式.

### ISSUE THREAD

**Issue by fy5220** [msdx/status-bar-compat#18]
附：开发者应该做的修改
如果开发者需要设置「状态栏黑色字符」的效果， 需要做以下几件事：

1. 在新的 MIUI 版本（即基于 Android 6.0 ，开发版 7.7.13 及以后版本）：
- 使用 `View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR` ，来设置「状态栏黑色字符」效果
- 同时要设置`WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS`，
- 并且无 `WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS`

参考实例：
    Window window = getWindow();
    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
    window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);

2. 在旧的MIUI版本
还有大量的米粉使用旧的MIUI版本，因此仍然需要使用 MIUI 原有的方法，即
    Window window = getWindow();
    window.addExtraFlags(MiuiWindowManager.LayoutParams.EXTRA_FLAG_STATUS_BAR_DARK_MODE);

为了保证在新旧版本的 MIUI 都能实现「状态栏黑色字符」的效果，需要开发者同时写上以上两种实现方法。

**Comment by renzhenfei** [comment]
Window window = getWindow();
window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);

结果是蓝底白字

**Comment by msdx** [comment]
@a48352433 即，对于MIUI，如果是6.0及以上需要两种方式都设置（见#9），否则采用MIUI的方法设置？

**Comment by a48352433** [comment]
@msdx 你看下这个网页http://www.miui.com/thread-8946673-1-1.html  miui更新后更改了方法.新版旧版不一样了.
我在MIUILightStatusBarImpl上自己改了下方法,测试了下.新旧小米手机均可以白底黑字了.但是方法没有用反射,没用过反射..不太会...
`
        public void setLightStatusBar(Window window, boolean lightStatusBar) {
            Class<? extends Window> clazz = window.getClass();
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                    window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
                    window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
                    window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
                } else {
                    Class<?> layoutParams = Class.forName("android.view.MiuiWindowManager$LayoutParams");
                    Field field = layoutParams.getField("EXTRA_FLAG_STATUS_BAR_DARK_MODE");
                    int darkModeFlag = field.getInt(layoutParams);
                    Method extraFlagField = clazz.getMethod("setExtraFlags", int.class, int.class);
                    extraFlagField.invoke(window, lightStatusBar ? darkModeFlag : 0, darkModeFlag);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
`

**Comment by a48352433** [comment]
还漏了判断不是lightStatusBar= =!

**Comment by msdx** [comment]
即对于MIUI，6.0及以上两个都调用，6.0以下使用MIUI的方式。

**Comment by fy5220** [comment]
@msdx http://www.miui.com/thread-8946673-1-1.html  这个文章是2017-7-10发布的..以后的系统如果是miui,且版本是6.0或6.0以上,使用系统原生方法实现.如果是miui,且系统版本小于6.0,则用miui自己的方法实现.就是你那个系统判断,- -换成0.51版本的就可以了.先判断是不是6.0,在判断是不是小米.手头上有两个小米手机.一个5.0一个6.0,自己改了下判断试了下.没问题.然后你那个#9.刚好把判断修改成了先小米,后安卓6.
也就是说之前的小米,不管什么版本,都是用小米自己的方法.但是7.10他们说只要是miui,且大于等于android6.那就按系统的来!!

**Comment by fy5220** [comment]
他们说这个改动会从miui   7.7.13 公测开发版开始生效（内测版本已生效）.但是之前版本那没办法了.然后就存在了miui android6以上一部分需要miui自己方法,一部分需要系统方法.所以最好是在miui 且android6以上两种方法都用上,以防万一

**Comment by msdx** [comment]
@a48352433 了解

**Comment by msdx** [comment]
0.5.2的版本是修复#9 的问题。我下周一改下，对miui把两种设置方式都加进来

**Comment by fy5220** [comment]
好的!

**Comment by msdx** [comment]
@a48352433 @renzhenfei 请试一下0.5.3-SNAPSHOT的版本。
需要添加仓库声明：
```gradle
maven { url "http://oss.jfrog.org/oss-snapshot-local/" }
```

**Comment by fy5220** [comment]
好的..我现在测试下..开了一上午会..测试完给你结果.10分钟

**Comment by fy5220** [comment]
测试了下.没有问题.在新老6.0上都试了,还有5.x上..4.x的小米找不到.就没试了!

**Comment by msdx** [comment]
@a48352433 OK, thanks. 稍后我将发布新版本。

**Comment by fy5220** [comment]
好的.谢谢了
