### ISSUE TITLE
怎么设置透明？

### ISSUE THREAD

**Issue by callmepeanut** [msdx/status-bar-compat#19]
传入透明颜色显示的还是白色

**Comment by msdx** [comment]
建议使用在style里声明状态栏透明的方式，在4.4.2以上可支持，同时不要使用本项目来设置状态栏。

**Comment by callmepeanut** [comment]
因为要在透明和白底切换，所以得放到程序里。自己写了设置透明的方法，但是切换成透明的后字体颜色还是黑色的（需要白色的），现在解决方案是先设置一个颜色把字体改为白色，再调用设置透明的方法~

**Comment by msdx** [comment]
可以直接参考项目里的代码。
其中，设置半透明：
```java
 window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
```
设置深浅色状态栏可参考[LightStatusBarCompat.java](https://github.com/msdx/status-bar-compat/blob/master/library/src/main/java/com/githang/statusbar/LightStatusBarCompat.java)的对应实现。

**Comment by callmepeanut** [comment]
OK，不过建议可以添加设置透明的方法

**Comment by msdx** [comment]
@callmepeanut 这是个好建议，我将抽时间在后面版本增加。

**Comment by msdx** [comment]
@callmepeanut 已经在0.6版本新增了设置透明的方法。
