### ISSUE TITLE
系统6.0上没效果

### ISSUE THREAD

**Issue by CJ070928** [msdx/status-bar-compat#2]
![image](https://cloud.githubusercontent.com/assets/19182942/16295494/d12e4540-3959-11e6-805a-3d14493c1e22.png)

如题

**Comment by msdx** [comment]
请问你的机型是？运行项目中的demo也是没有效果吗？

**Comment by msdx** [comment]
由于没有更详细的信息，该issue将在10后择日关闭。
如果关闭后有信息补充，请再度打开该issue。

**Comment by sdfasffsdf** [comment]
StatusBarLollipopImpl
请问这个class 在代码用并没有调用到，这是为什么呢？

**Comment by msdx** [comment]
因为在实际开发中发现它在华为p7 android 5.1上不奏效，为能适配更多机型所以最终没有采用它。
另外与主题无关的回复请新开issue。

**Comment by msdx** [comment]
由于题主未提供更详细信息，并且截图不是运行本项目的demo，无法判断是不适配还是使用不当引起，先将issue关闭，如果有信息补充再打开。

**Comment by msdx** [comment]
显示的灰色像是直接使用R.color.xxx而非使用颜色值所设置的颜色。
