### ISSUE TITLE
状态栏字体颜色如何变黑

### ISSUE THREAD

**Issue by inkfishzhong** [msdx/status-bar-compat#23]
您好，我用了这个框架后，能成功改版状态栏颜色，但字体是灰色的，UI图上是黑色的，能改吗？

**Comment by msdx** [comment]
请参考项目README相关说明：[深色状态栏图标设置支持](https://github.com/msdx/status-bar-compat#%E6%B7%B1%E8%89%B2%E7%8A%B6%E6%80%81%E6%A0%8F%E5%9B%BE%E6%A0%87%E8%AE%BE%E7%BD%AE%E6%94%AF%E6%8C%81)

**Comment by inkfishzhong** [comment]
不好意思，没看清楚，谢谢
