### ISSUE TITLE
在4.4的红米手机上，DrawLayout中，statusbar颜色设置后会和Toolbar重叠

### ISSUE THREAD

**Issue by aiceking** [msdx/status-bar-compat#24]

**Comment by msdx** [comment]
能附图吗？

**Comment by aiceking** [comment]
![image](https://user-images.githubusercontent.com/30397251/33253902-f25641f6-d380-11e7-984f-1311fe259034.jpg)

**Comment by aiceking** [comment]
我自己做了处理，就是在4.4版本的时候给ToolBar设一个MarginTop 25dp，留出statusBar的高度，在网上查的DrawLayout貌似在4.4会出现这个问题

**Comment by msdx** [comment]
DrawerLayout 它本身会设置让其占满整个空间（包含系统状态栏），即使我这边设了fitsSystemWindow也是一样，所以可以修改布局，根布局使用一个FrameLayout，里面再使用DrawerLayout

**Comment by msdx** [comment]
如果你是自己设置marginTop，建议在代码上，获取状态栏高度，并根据系统版本及设备机型等条件来设置，而不要写死，以避免兼容问题。

**Comment by aiceking** [comment]
解决思路差不多，这个25dp是一般状态栏的高度，我现在也是在代码里获取的，解决就好啦
