### ISSUE TITLE
小米 MIX2 MIUIV9无法调整状态栏颜色

### ISSUE THREAD

**Issue by TheStar4Fate** [msdx/status-bar-compat#26]
![_20171218111150](https://user-images.githubusercontent.com/7358871/34088420-468cc2b8-e3e4-11e7-8ba7-021f2e6284d7.png)

![_20171218110910](https://user-images.githubusercontent.com/7358871/34088395-253d7530-e3e4-11e7-9cfc-55adabf34bd4.jpg)

**Comment by ldljheropt** [comment]
只需在 AndroidManifest.xml 的 application 节点下添加 android:resizeableActivity="true" 即可，
 <application
    android:resizeableActivity="true"
</application>

或者加 <meta-data android:name="android.max_aspect"
    android:value="ratio_float"/>

其中ratio_float为浮点数，官方建议为2.1或更大，因为18.5：9=2.055555555……，如果日后出现纵横比更大的手机，此值将会更大。

参见：http://blog.csdn.net/qq_37237245/article/details/73350436

**Comment by TheStar4Fate** [comment]
好的，我试一下
