### ISSUE TITLE
红米2a   android 4.4  没用android的toolbar  自己在activity的布局里直接一起弄的bar

### ISSUE THREAD

**Issue by xinyangmaojian** [msdx/status-bar-compat#31]
问题效果如下图
[问题](https://weekimwee.oss-cn-shanghai.aliyuncs.com/xg.png)
[手机型号](https://weekimwee.oss-cn-shanghai.aliyuncs.com/xg.png)

**Comment by xinyangmaojian** [comment]
[手机型号](https://weekimwee.oss-cn-shanghai.aliyuncs.com/xh.png)

**Comment by xinyangmaojian** [comment]
[手机型号截图](https://weekimwee.oss-cn-shanghai.aliyuncs.com/xh.jpg)

**Comment by xinyangmaojian** [comment]
红米4   android6.0正常

**Comment by msdx** [comment]
是在 setContentView 之后调用的吗？

**Comment by msdx** [comment]
请仔细看 README：https://github.com/msdx/status-bar-compat#%E4%BB%A3%E7%A0%81%E8%B0%83%E7%94%A8
