### ISSUE TITLE
魅族手机第一次打开activity状态栏设置失效

### ISSUE THREAD

**Issue by kinkenrin** [msdx/status-bar-compat#32]
魅族手机第一次打开activity状态栏颜色设置失效
关闭activity后 再进入就设置成功了

**Comment by msdx** [comment]
系统版本及你的调用代码？

**Comment by kinkenrin** [comment]
android 7.0
调用代码如下
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        super.onCreate(savedInstanceState);
        setContentView(getContentViewResId());
        int sobot_status_bar_color = getResources().getColor(R.color.sobot_status_bar_color);
        if (sobot_status_bar_color != 0) {
            try {
                StatusBarCompat.setStatusBarColor(this, sobot_status_bar_color);
            } catch (Exception e) {
                //请传入正确的颜色值
            }
        }
   ......
}
我调试了一下发现使用了StatusBarMImpl()这个代理，我现在修改了代码，判断是魅族的手机就用StatusBarKitkatImpl这个代理，就没有这个问题
    另外，在5.0的魅族手机使用StatusBarLollipopImpl()这个代理也会出现这个问题 似乎这个是魅族本身存在的问题。
修改后代码如下：
static {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !isMeizu()) {
            IMPL = new StatusBarMImpl();
        } /*else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && !isEMUI()) {
            IMPL = new StatusBarLollipopImpl();
        } */else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            IMPL = new StatusBarKitkatImpl();
        } else {
            IMPL = new IStatusBar() {
                @Override
                public void setStatusBarColor(Window window, @ColorInt int color) {
                }
            };
        }
    }

**Comment by msdx** [comment]
嗯，魅族对状态栏的修改很让人头疼，经历过它的flyme的几个版本，每个版本都改得不一样，比较难适配全各种版本。
