### ISSUE TITLE
Readme 已知问题 可能会出现状态栏与标题栏之间有一个与状态栏同样大小的间距

### ISSUE THREAD

**Issue by 2017398956** [msdx/status-bar-compat#34]
如果 这个activity 没有 actionbar 下面的那个设置无效

**Comment by msdx** [comment]
是全面屏吗？

**Comment by 2017398956** [comment]
noactionbar

**Comment by 2017398956** [comment]
![image](https://user-images.githubusercontent.com/12185078/42252380-e2e8f71e-7f6e-11e8-8af8-a3b098cb0b59.png)
有一条白色 Android 4.4

**Comment by msdx** [comment]
能否附上机型，布局及调用代码？

**Comment by 2017398956** [comment]
是在逍遥模拟器上出现的。。。机型什么的都无所谓吧，因为原布局在项目里很复杂，我简单描述说下：状态栏下就是个整屏 webview ，设置状态栏颜色 按钮是通过js 调用你写的方法，如果不能解决就算了，只有模拟器出现这种情况

**Comment by Jevis** [comment]
这个状态在小米 魅族 7.0 是必现的

**Comment by msdx** [comment]
@Jevis 机型是什么？是全面屏吗？
目前用的一个红米测试机，7.1.2，没有这个问题。

**Comment by Jevis** [comment]
机型是小米5s 和魅族5 pro ，不是全面屏 不过我是配合QMUI框架一起使用的， 我是在tab+viewpager中去动态设置fragment的状态栏颜色。

**Comment by msdx** [comment]
@Jevis 能否提供以下内容？
1. 表现该问题的运行截图
2. 使用 demo 运行的结果截图
3. 布局文件的描述（主要是第一、二层所使用的布局）

**Comment by msdx** [comment]
@Jevis 添加了NoActionBar的demo，在我这里的开发机器上未发现此问题。
建议用开发者选项里的布局边界查看工具，看下这里是webview的padding还是margin。如果是padding，则手动设置一下。如果是margin，试下调用 `resetActinBarContainerTopMargin(window, webViewId)`
