### ISSUE TITLE
多个fragment 其中三个为白底黑字 一个为透明白色字体 当切换到透明的那个fragment 颜色为黑色怎样设置为白色

### ISSUE THREAD

**Issue by dongtianlong** [msdx/status-bar-compat#36]

**Comment by msdx** [comment]
@dongtianlong 试下setLightStatusBar

**Comment by dongtianlong** [comment]
![0 c n 39e a s1hg _2m](https://user-images.githubusercontent.com/21264012/49851710-f8b5bf00-fe1c-11e8-8b31-babd8207e6a5.png)
我是用的是StatusBarCompat.setTranslucent(getWindow(),true); 单独作为activity的时候字体是白色 但是出现在fragment中切换的时候 字体是黑色 怎样是字体在fragment中也是白色

**Comment by msdx** [comment]
> @dongtianlong 试下setLightStatusBar

看这里。

**Comment by msdx** [comment]
经尝试，`StatusBarCompat.setLightStatusBar(window, isLightStatusBar);`可以设置，故关闭此问题。
