### ISSUE TITLE
谷歌pixel的模拟器会把布局给顶上去

### ISSUE THREAD

**Issue by SanChunAndrroid** [msdx/status-bar-compat#38]
谷歌pixel的模拟器会把布局给顶上去

**Comment by SanChunAndrroid** [comment]
是api19的

**Comment by msdx** [comment]
@SanChunAndrroid 请附上demo运行截图

**Comment by SanChunAndrroid** [comment]
@msdx 实际项目不方便

**Comment by SanChunAndrroid** [comment]
@msdx 是单activity加多fragment架构的  然后在MainActivity加这一句就会被顶上去

**Comment by msdx** [comment]
请附上你的调用代码及Activity根布局代码。

**Comment by SanChunAndrroid** [comment]
@msdx 链接：https://github.com/Horrarndoo/YiZhi
就是放到这个demo的MainActivity或者BaseCompatactivity里面会有这个问题 其他的版本并不会

**Comment by msdx** [comment]
@SanChunAndrroid 我在这里并没有看到你调用 的代码，看不到如何调用，我无法准确判断。
另外我看到这个项目中的MainActivity用了DrawerLayout，请参考这里检查一下：https://github.com/msdx/status-bar-compat/issues/25#issuecomment-349532257

**Comment by SanChunAndrroid** [comment]
@msdx 已解决，谢谢，还真的是DrawerLayout外层加个帧布局就OK了
