### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by hzka** [msdx/status-bar-compat#43]
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of tassk ':app:processDebugResources'.
Could not resolve all task dependencies for configurationh ':app:debugRuntimeClasspath'.
Could not resolve com.githang:status-bar-coompat:latest. integration.
Required by:
> Failed to list versions for com.githang:sstatus-bar-compat.
> Unable to load Maven meta-data from https://dl.bintray..com/aweme-open-sdk-team/public/com/githang/status-bar-compat/maven-metadata.xml.
> Could not get resource 'https://dl.bintray.com/aweme-oppen-sdk-team/public/com/githang/status-bar-compat/maven-metadata.xml'.
> Could not GET 'https://dl.bintray.com/aweme-opern-sdk-team/public/com/githang/status-bar-compat/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by msdx** [comment]
这是执行发布任务的时候bintray挂了。不要执行发布任务，把发布任务移除就可以了。

**Comment by hzka** [comment]
您的信件我已经收到，我会尽快给您回复的！
