### ISSUE TITLE
小米5状态栏字体颜色不能改哦

### ISSUE THREAD

**Issue by sunfusheng** [msdx/status-bar-compat#6]
请你看下，回复我，谢谢

**Comment by msdx** [comment]
@sfsheng0322 麻烦附上你的设备的MANUFACTURER信息，看内容是什么.
还有，麻烦附一下系统版本信息。

**Comment by sunfusheng** [comment]
我把你的源码clone下来改了个地方，现在在小米5（Android 版本 6.0.1）上可以了。
你在StatusBarKitkatImpl文件setStatusBarColor()函数里加上下面这两句吧：
StatusBarCompat.setFitsSystemWindows(window, true);
StatusBarCompatFlavorRom.setLightStatusBar(window, lightStatusBar);

**Comment by msdx** [comment]
@sfsheng0322 在`StatusBarKitkatImpl`里本身就有对这两行代码的调用。另外，android 6.0.1执行的不是这里，是StatusBarMImpl

**Comment by sunfusheng** [comment]
是啊，在Android 6.0 应该执行是StatusBarMImpl，但我在StatusBarKitkatImpl文件setStatusBarColor()函数里加上那两句就OK啦，我再看看代码哈，谢谢你。

**Comment by msdx** [comment]
@sfsheng0322 你是直接引用我这里的aar的吗？

**Comment by msdx** [comment]
那个类里本来就有对这两行代码的调用，不需要再加。
