### ISSUE TITLE
不支持对瓦戈卓越手机设置深色的状态栏图标

### ISSUE THREAD

**Issue by zhufui** [msdx/status-bar-compat#7]
在5.1.1的机器上，我将状态栏的颜色设置为白色的，状态栏字体的颜色没有变成深色的

**Comment by msdx** [comment]
什么机型？

**Comment by zhufui** [comment]
卓越手机

**Comment by zhufui** [comment]
瓦戈做的手机

**Comment by msdx** [comment]
字体变深色需要Android 6.0以上才支持，其他机型目前只有flyme及miui有开放相关接口。

**Comment by zhufui** [comment]
好的，知道了，谢谢啊

**Comment by msdx** [comment]
@zhufui 那我先关掉issue了。要是该设备的rom以后也开放了接口，可以再到这里重新打开issue。

**Comment by zhufui** [comment]
恩恩，好的

**Comment by msdx** [comment]
API 23以下没有设置深色图标的接口。
