### ISSUE TITLE
不支持小米6.0及7.0的手机，代码判断bug

### ISSUE THREAD

**Issue by muyi-yang** [msdx/status-bar-compat#9]
问题机型截图：
![image](https://cloud.githubusercontent.com/assets/16754211/23444372/a254f72e-fe6f-11e6-8f59-7c2eed21d8ed.png)

如下代码导致MIUI和Flyme没有效果：
static {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            IMPL = new MLightStatusBarImpl();
        } else if (MIUILightStatusBarImpl.isMe()) {
            IMPL = new MIUILightStatusBarImpl();
        } else if (MeizuLightStatusBarImpl.isMe()) {
            IMPL = new MeizuLightStatusBarImpl();
        } else {
            IMPL = new ILightStatusBar() {
                @Override
                public void setLightStatusBar(Window window, boolean lightStatusBar) {
                }
            };
        }
    }
应该先判断是否MIUI和Flyme再判断是否大于6.0，否则小米和魅族的6.0以上手机依然走的是Google原生API，则设置无效；小米魅族6.0以上手机也需走各自特性的设置方式；

**Comment by msdx** [comment]
@576049635 你好，请问小米及魅族的方式也支持它们5.0以下的手机吗？因为我手头没有对应的测试机可以测试这个问题。

**Comment by muyi-yang** [comment]
我这边是有小米手机，5.0  7.0 系统的，测试通过，也查了一下官方，MIUI 6.0版本开始支持，这个跟android 系统版本貌似无关，只要是MIUI 6.0以上都是这种写法，，魅族暂时没有手机，但猜测应该是一样，它应该是跟Flyme版本有关

**Comment by msdx** [comment]
它们5.0以下的手机也可以用miui或flyme 方法吗？

**Comment by muyi-yang** [comment]
小米测试4.4也是可行的，小米看的不是android 系统版本，看的是 MIUI 版本，只要MIUI 6.0 以上则支持

**Comment by msdx** [comment]
@576049635 OK，感谢测试，因为明天要出差，我下周一更新一下。到时先更新小米的判断。

**Comment by msdx** [comment]
@576049635 已修改，能否帮忙测试一下看是否通过？
```
 compile 'com.githang:status-bar-compat:0.5.2-SNAPSHOT'
```

**Comment by ayuhani** [comment]
同样是小米5 为什么我的没有7.0推送呢

**Comment by msdx** [comment]
@ayuhani 这个问题，你可以在小米论坛问。。。

**Comment by ayuhani** [comment]
@msdx 小米5使用0.5.1之后设置白色，状态栏的确变成了白色，但是状态栏的图标依然是白色，一片白..
改成'com.githang:status-bar-compat:0.5.2-SNAPSHOT'之后，报错提示找不到0.5.2.
使用的方法是StatusBarCompat.setStatusBarColor(this, Color.parseColor("#ffffff"), true);

**Comment by msdx** [comment]
@ayuhani 使用SNAPSHOT版本你需要添加此声明到`repositories`节点：
```gradle
 maven { url "http://oss.jfrog.org/oss-snapshot-local/" }
```

**Comment by ayuhani** [comment]
@msdx 小米5 安卓版本6.0 ；红米note2 安卓版本5.1 目前测试成功，没有其他品牌手机，无法测试。
模拟器使用正常。

**Comment by msdx** [comment]
@ayuhani 感谢测试。已发布0.5.2版本至jcenter。
